#ifndef _CONTROL_H_
#define _CONTROL_H_

/* Definitions of manifest constants */
typedef enum {	WHILE, LPAREN, RPAREN, LCURLY, RCURLY, IF, ELSE,
		REPEAT, SEMICOL, PAUSE, OUTSTRING, OUTINT, LCLICK, RCLICK,
		LRELEASE, RRLEASE, UP, DOWN, LEFT, RIGHT, PRESSKEY, RELEASEKEY,
		ID, EQASS, OR, AND, EQCOMP, NE, LT, LE, GT, GE, ADD, SUB,
		MUL, DIV, MOD, OPP, INT, ININT, MOUSEPOSX, MOUSEPOSY,
		INSTRING, STRING, STRING_T, INT_T
	     } TERMINALS;
	     
typedef enum {DOTO_} NON_TERMINALS;




#endif
